kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master
  namespace: vaibhav
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locustsync
          imagePullPolicy: Always
          image: image_name
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          env:
          - name: LOCUST_MODE
            value: "master"
          - name: CLIENT_ID
            value: "ADD_ID"
          - name: CLIENT_SECRET
            value: "ADD_SECRET"
          - name: XSUAA_URL
            value: "ADD_URL"
          - name: API_NAMESPACE
            value: "api"
          - name: RESOURCE
            value: "image"
          - name: API_VERSION
            value: "v2"
          - name: HOST
            value: "HOST_URL"
          - name: NUMBER_SLAVES
            value: "10"
          - name: NUM_THREADS_FROM
            value: "1"
          - name: NUM_REQUESTS
            value: "5"
          - name: MIN_WAIT
            value: "0"
          - name: MAX_WAIT
            value: "0"
      imagePullSecrets:
      - name: docker-registry-secret